[project]
name = "api_service"
version = "1.0.0"
description = "The temperature and hymidity api service"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"